[package]
name = "glider-kitchen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glider-kitchen-ai = { path = "../glider-kitchen-ai" }
