name: "Pre-commit Checks"

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    name: "Run pre-commit Hooks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install stable version
        run: rustup default stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
